In [2]:
#
import torch
import torch.nn as nn
#
inputs = torch . tensor( [ [ 0.0 ] , [ 1.0 ] ] )
#
print( inputs )
#

tensor([[0.],
        [1.]])


In [3]:
weights = (-1,1)
learning_rate = 0.1

model = nn.Sequential(
    nn.Linear(1, 1, bias=True),
    nn.Sigmoid()
)

lossTimeX = []
lossTimeY = []

# with torch.no_grad():
#     model[0].weight.fill_(weights[1])
#     model[0].bias.fill_(weights[0])
#     print(model(inputs))

outputs = torch.tensor([[1], [0]])

loss_fn = nn.MSELoss(reduction='sum')

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(10000):
    loss = loss_fn(model(inputs), outputs.float())
    if epoch % 100 == 0:
        print(epoch, loss.item())
        print("Item loss:",loss.item())

    optimizer.zero_grad()

    loss.backward()
#     with torch.no_grad():
#         for param in model.parameters():
#             print(param.grad)
    optimizer.step()
#     print("After step")
#     with torch.no_grad():
#         for param in model.parameters():
#             print(param.grad)

0 0.5729255080223083
Item loss: 0.5729255080223083
100 0.1799175888299942
Item loss: 0.1799175888299942
200 0.1009596735239029
Item loss: 0.1009596735239029
300 0.06685557961463928
Item loss: 0.06685557961463928
400 0.04889601469039917
Item loss: 0.04889601469039917
500 0.038099728524684906
Item loss: 0.038099728524684906
600 0.030995849519968033
Item loss: 0.030995849519968033
700 0.026010069996118546
Item loss: 0.026010069996118546
800 0.022338837385177612
Item loss: 0.022338837385177612
900 0.019533872604370117
Item loss: 0.019533872604370117
1000 0.01732712984085083
Item loss: 0.01732712984085083
1100 0.01554948277771473
Item loss: 0.01554948277771473
1200 0.014089261181652546
Item loss: 0.014089261181652546
1300 0.012869970872998238
Item loss: 0.012869970872998238
1400 0.011837628670036793
Item loss: 0.011837628670036793
1500 0.010953022167086601
Item loss: 0.010953022167086601
1600 0.010187109000980854
Item loss: 0.010187109000980854
1700 0.009517913684248924
Item loss: 0.0095179

In [4]:
with torch.no_grad():
    for param in model.parameters():
        print(param)

Parameter containing:
tensor([[-7.2381]], requires_grad=True)
Parameter containing:
tensor([3.5132], requires_grad=True)
