In [1]:
#
import torch
import torch.nn as nn
#
inputs = torch . tensor( [ [ 0.0 ] , [ 1.0 ] ] )
#
print( inputs )
#

tensor([[0.],
        [1.]])


In [2]:
weights = (-1,1)

model = nn.Sequential(
    nn.Linear(1, 1, bias=True),
    nn.Sigmoid()
)

# with torch.no_grad():
#     model[0].weight.fill_(weights[1])
#     model[0].bias.fill_(weights[0])
#     print(model(inputs))

outputs = torch.tensor([[1], [0]])

loss_fn = nn.MSELoss(reduction='sum')
predictions = model(inputs)
loss = loss_fn(predictions, outputs.float())
print("Loss item:", loss.item())
print("Grad function:", loss.grad_fn)

model.zero_grad()
loss.backward()

with torch.no_grad():
    for param in model.parameters():
        print(param)
        print("Param.grad", param.grad)

Loss item: 0.44986212253570557
Grad function: <MseLossBackward object at 0x7f3400550130>
Parameter containing:
tensor([[-0.7828]], requires_grad=True)
Param.grad tensor([[0.0672]])
Parameter containing:
tensor([-0.5685], requires_grad=True)
Param.grad tensor([-0.2275])
