In [10]:
#
import torch
import torch.nn as nn
#
inputs = torch . tensor( [ [ 0.0 ] , [ 1.0 ] ] )
#
print( inputs )
#

tensor([[0.],
        [1.]])


In [11]:
weights = (-1,1)
learning_rate = 0.1

model = nn.Sequential(
    nn.Linear(1, 1, bias=True),
    nn.Sigmoid()
)

lossTimeX = []
lossTimeY = []

# with torch.no_grad():
#     model[0].weight.fill_(weights[1])
#     model[0].bias.fill_(weights[0])
#     print(model(inputs))

outputs = torch.tensor([[1], [0]])

loss_fn = nn.MSELoss(reduction='sum')

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

loss = loss_fn(model(inputs), outputs.float())

print("Item loss:",loss.item())
lossTimeY.append(loss.item())

model.zero_grad()
optimizer.zero_grad()
print("Before step")
with torch.no_grad():
    for param in model.parameters():
        print(param.grad)
loss.backward()
optimizer.step()
print("After step")
with torch.no_grad():
    for param in model.parameters():
        print(param.grad)

Item loss: 0.5610109567642212
Before step
None
None
After step
tensor([[0.2963]])
tensor([0.1459])


In [12]:
with torch.no_grad():
    for param in model.parameters():
        print(param.grad)

tensor([[0.2963]])
tensor([0.1459])
