In [18]:
#
import torch
import torch.nn as nn
import math
#
inputs = torch . tensor( [ [ 0.0, 0 ] , [ 1.0,1 ], [1,0], [0,1] ] )
#
print( inputs )
#

tensor([[0., 0.],
        [1., 1.],
        [1., 0.],
        [0., 1.]])


In [19]:
weights = (-1,1)
learning_rate = 0.1

model = nn.Sequential(
    nn.Linear(2, 1, bias=True),
    nn.Sigmoid()
)

outputs = torch.tensor([[0], [1], [0], [0]])

loss_fn = nn.MSELoss(reduction='sum')

model.zero_grad()

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

with torch.no_grad():
    for param in model.parameters():
        print(param)

for epoch in range(10000):
    loss = loss_fn(model(inputs), outputs.float())
    optimizer.zero_grad()

    loss.backward()
    optimizer.step()
print()
with torch.no_grad():
    for param in model.parameters():
        print(param)
        
print()
print(loss.item())

Parameter containing:
tensor([[-0.2852,  0.6827]], requires_grad=True)
Parameter containing:
tensor([0.3116], requires_grad=True)

Parameter containing:
tensor([[6.2721, 6.2721]], requires_grad=True)
Parameter containing:
tensor([-9.4979], requires_grad=True)

0.004979147110134363
